本教程大部分内容参考自

📌 [deep-learning-with-python-notebooksl](https://github.com/fchollet/deep-learning-with-python-notebooks)

In [1]:
import tensorflow
tensorflow.__version__

'2.8.0'


# <b>1 <span style='color:#F1C40F'>|</span> 准备数据</b>
<b></b>
<div style="color:white;display:fill;border-radius:8px;
            background-color:#323232;font-size:150%;
            font-family:Nexa;letter-spacing:0.5px">
    <p style="padding: 8px;color:white;"><b>准备numpy.ndarray类型的数据</b></p>
</div>


### 导入内置的Boston housing dataset

这个数据提供404个训练样本和102个测试样本. 每个样本被13个特征刻画：

- 1. Per capita crime rate.
- 2. Proportion of residential land zoned for lots over 25,000 square feet.
- 3. Proportion of non-retail business acres per town.
- 4. Charles River dummy variable (= 1 if tract bounds river; 0 otherwise).
- 5. Nitric oxides concentration (parts per 10 million).
- 6. Average number of rooms per dwelling.
- 7. Proportion of owner-occupied units built prior to 1940.
- 8. Weighted distances to five Boston employment centres.
- 9. Index of accessibility to radial highways.
- 10. Full-value property-tax rate per $10,000.
- 11. Pupil-teacher ratio by town.
- 12. 1000 * (Bk - 0.63) ** 2 where Bk is the proportion of Black people by town.
- 13. % lower status of the population.

标签的涵义：median values of owner-occupied homes, in thousands of dollars:

In [3]:
from tensorflow.keras.datasets import boston_housing

(train_data, train_targets), (test_data, test_targets) =  boston_housing.load_data()

In [4]:
type(train_data), train_data.shape

(numpy.ndarray, (404, 13))

In [37]:
train_data

array([[-0.27224633, -0.48361547, -0.43576161, ...,  1.14850044,
         0.44807713,  0.8252202 ],
       [-0.40342651,  2.99178419, -1.33391162, ..., -1.71818909,
         0.43190599, -1.32920239],
       [ 0.1249402 , -0.48361547,  1.0283258 , ...,  0.78447637,
         0.22061726, -1.30850006],
       ...,
       [-0.40202987,  0.99079651, -0.7415148 , ..., -0.71712291,
         0.07943894, -0.67776904],
       [-0.17292018, -0.48361547,  1.24588095, ..., -1.71818909,
        -0.98764362,  0.42083466],
       [-0.40422614,  2.04394792, -1.20161456, ..., -1.30866202,
         0.23317118, -1.15392266]])

In [7]:
train_targets

array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
       17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
       32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
       23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
       12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.5, 24.8, 19.1,
       22. , 14.5, 11. , 32. , 29.4, 20.3, 24.4, 14.6, 19.5, 14.1, 14.3,
       15.6, 10.5,  6.3, 19.3, 19.3, 13.4, 36.4, 17.8, 13.5, 16.5,  8.3,
       14.3, 16. , 13.4, 28.6, 43.5, 20.2, 22. , 23. , 20.7, 12.5, 48.5,
       14.6, 13.4, 23.7, 50. , 21.7, 39.8, 38.7, 22.2, 34.9, 22.5, 31.1,
       28.7, 46. , 41.7, 21. , 26.6, 15. , 24.4, 13.3, 21.2, 11.7, 21.7,
       19.4, 50. , 22.8, 19.7, 24.7, 36.2, 14.2, 18.9, 18.3, 20.6, 24.6,
       18.2,  8.7, 44. , 10.4, 13.2, 21.2, 37. , 30.7, 22.9, 20. , 19.3,
       31.7, 32. , 23.1, 18.8, 10.9, 50. , 19.6,  5. , 14.4, 19.8, 13.8,
       19.6, 23.9, 24.5, 25. , 19.9, 17.2, 24.6, 13

<div style="color:white;display:fill;border-radius:8px;
            background-color:#323232;font-size:150%;
            font-family:Nexa;letter-spacing:0.5px">
    <p style="padding: 8px;color:white;"><b>对数据进行预处理</b></p>
</div>

In [6]:
mean = train_data.mean(axis=0)
train_data -= mean
std = train_data.std(axis=0)
train_data /= std

test_data -= mean
test_data /= std



# <b>2 <span style='color:#F1C40F'>|</span> 网络的设定</b>
<b></b>
<div style="color:white;display:fill;border-radius:8px;
            background-color:#323232;font-size:150%;
            font-family:Nexa;letter-spacing:0.5px">
    <p style="padding: 8px;color:white;"><b>调用tensorflow.keras.models定义网络类型</b></p>
</div>
<div style="color:white;display:fill;border-radius:8px;
            background-color:#323232;font-size:150%;
            font-family:Nexa;letter-spacing:0.5px">
    <p style="padding: 8px;color:white;"><b>调用tensorflow.keras.layers定义网络层</b></p>
</div>

In [7]:
from tensorflow.keras import models
from tensorflow.keras import layers
model = models.Sequential()
model.add(layers.Dense(64, activation='relu',
                       input_shape=(train_data.shape[1],)))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(1))


<div style="color:white;display:fill;border-radius:8px;
            background-color:#323232;font-size:150%;
            font-family:Nexa;letter-spacing:0.5px">
    <p style="padding: 8px;color:white;"><b>利用compile方法设定学习细节</b></p>
</div>

In [8]:
model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])


<div style="color:white;display:fill;border-radius:8px;
            background-color:#323232;font-size:150%;
            font-family:Nexa;letter-spacing:0.5px">
    <p style="padding: 8px;color:white;"><b>利用summary查看网络</b></p>
</div>

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                896       
                                                                 
 dense_1 (Dense)             (None, 64)                4160      
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 5,121
Trainable params: 5,121
Non-trainable params: 0
_________________________________________________________________


# <b>3 <span style='color:#F1C40F'>|</span> 网络的学习，使用，存储等</b>
<b></b>
<div style="color:white;display:fill;border-radius:8px;
            background-color:#323232;font-size:150%;
            font-family:Nexa;letter-spacing:0.5px">
    <p style="padding: 8px;color:white;"><b>利用fit函数学习网络</b></p>
</div>

其中参数verbose控制日志显示的方式：

- verbose = 0 为不在标准输出流输出日志信息

- verbose = 1 为输出进度条记录

- verbose = 2 为每个epoch输出一行记录

In [10]:
model.fit(train_data, train_targets, epochs=80, batch_size=16, verbose=1)

Epoch 1/80
26/26 [==============================] - 1s 1ms/step - loss: 471.5072 - mae: 19.6347
Epoch 2/80
26/26 [==============================] - 0s 1ms/step - loss: 292.8292 - mae: 14.5650
Epoch 3/80
26/26 [==============================] - 0s 997us/step - loss: 131.1487 - mae: 8.9504
Epoch 4/80
26/26 [==============================] - 0s 1ms/step - loss: 54.9915 - mae: 5.3494
Epoch 5/80
26/26 [==============================] - 0s 2ms/step - loss: 35.6886 - mae: 4.2751
Epoch 6/80
26/26 [==============================] - 0s 1ms/step - loss: 28.3350 - mae: 3.7442
Epoch 7/80
26/26 [==============================] - 0s 1ms/step - loss: 23.9568 - mae: 3.4074
Epoch 8/80
26/26 [==============================] - 0s 1ms/step - loss: 21.3755 - mae: 3.1627
Epoch 9/80
26/26 [==============================] - 0s 933us/step - loss: 19.5350 - mae: 3.0375
Epoch 10/80
26/26 [==============================] - 0s 959us/step - loss: 17.8063 - mae: 2.8909
Epoch 11/80
26/26 [=============================

<div style="color:white;display:fill;border-radius:8px;
            background-color:#323232;font-size:150%;
            font-family:Nexa;letter-spacing:0.5px">
    <p style="padding: 8px;color:white;"><b>利用predict函数获得预测或利用evaluate函数进行模型评估</b></p>
</div>


In [12]:
predictions = model.predict(test_data)
predictions

array([[ 7.8969502],
       [19.283857 ],
       [21.977648 ],
       [31.459055 ],
       [25.159746 ],
       [21.44304  ],
       [25.948652 ],
       [21.687681 ],
       [19.345346 ],
       [22.11231  ],
       [18.026438 ],
       [16.792923 ],
       [15.982572 ],
       [41.8082   ],
       [19.51135  ],
       [20.465292 ],
       [25.815832 ],
       [18.721766 ],
       [18.909176 ],
       [27.554667 ],
       [11.2418585],
       [15.597343 ],
       [21.866121 ],
       [15.2266445],
       [19.851734 ],
       [24.8961   ],
       [29.052464 ],
       [29.254467 ],
       [11.189183 ],
       [20.180914 ],
       [19.788334 ],
       [15.538543 ],
       [34.27071  ],
       [24.394644 ],
       [18.290651 ],
       [ 8.429926 ],
       [17.254904 ],
       [17.69568  ],
       [19.708368 ],
       [25.134775 ],
       [29.228518 ],
       [27.705095 ],
       [13.965707 ],
       [42.502842 ],
       [28.914915 ],
       [25.085283 ],
       [27.03693  ],
       [17.68

In [13]:
test_mse_score, test_mae_score = model.evaluate(test_data, test_targets, verbose = 0)
test_mae_score

2.691445827484131

<div style="color:white;display:fill;border-radius:8px;
            background-color:#323232;font-size:150%;
            font-family:Nexa;letter-spacing:0.5px">
    <p style="padding: 8px;color:white;"><b>利用tensorflow.keras.models来获得单独每一层的输出</b></p>
</div>


In [14]:
from tensorflow.keras.models import Model 
dense1_layer_model = Model(inputs=model.input ,outputs=model.get_layer('dense_1').output) 
test_feas_dense1 = dense1_layer_model.predict(test_data)
test_feas_dense1

array([[1.1697562, 1.4366028, 0.6576094, ..., 1.3842618, 2.3077302,
        0.       ],
       [2.125175 , 1.86264  , 2.0705428, ..., 2.0486794, 2.0261357,
        0.2121315],
       [2.8507903, 1.8717936, 2.8531046, ..., 2.2313676, 2.5353532,
        0.3428657],
       ...,
       [5.1441593, 3.7089047, 5.3668675, ..., 6.0201507, 3.7497175,
        1.1841226],
       [3.2884667, 2.2568932, 3.7434158, ..., 4.4131627, 2.7536535,
        0.9499691],
       [2.3375585, 1.563706 , 2.5341387, ..., 1.8903722, 1.5981396,
        0.       ]], dtype=float32)

<div style="color:white;display:fill;border-radius:8px;
            background-color:#323232;font-size:150%;
            font-family:Nexa;letter-spacing:0.5px">
    <p style="padding: 8px;color:white;"><b>调用save和load_model实现模型的存储与复用</b></p>
</div>

### 存储为TensorFlow SavedModel 格式

调用save命令，我们将看到一个first_model的目录被创建，其中包括：

├── assets

├── saved_model.pb

└── variables

    ├── variables.data-00000-of-00001

    └── variables.index

├── keras_metadata.pb

其中 assets 是一个可选的目录，用于存放模型运行所需的辅助文件，比如字典文件等。 variables 目录下存放的是模型权重的检查点文件，模型的所有权重信息均保存在该目录下。 saved_model.pb 文件中包含了模型的结构以及训练的配置信息如优化器，损失以及指标等信息。keras_metadata.pb则实现了能够令模型被成功还原成Keras model。
   

In [16]:
model.save('first_model')

INFO:tensorflow:Assets written to: first_model\assets


In [18]:
loaded_model = tensorflow.keras.models.load_model("first_model")

In [19]:
test_mse_score, test_mae_score = loaded_model.evaluate(test_data, test_targets, verbose = 0)
test_mae_score

2.691445827484131

### 存储为Keras H5 格式

In [20]:
tensorflow.keras.models.save_model(model, "first_model.h5")

In [21]:
loaded_model = tensorflow.keras.models.load_model("first_model.h5")

In [22]:
test_mse_score, test_mae_score = loaded_model.evaluate(test_data, test_targets, verbose = 0)
test_mae_score

2.691445827484131